pipeline:
  name: Gopi
  identifier: Gopi
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Gopi
        identifier: Gopi
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "Hi Gopi"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
